Various text changes
DazedMTL/NightmareKnight pull request #8
Opened 2023-12-26 02:02 UTC by lostcause120

Various text changing ranging from minor to major changes to text lines

Minor Change Examples: 
- adding parenthesis for inner rain thoughts
- pronoun consistency changes
- changing newline locations to prevent text from being cut off
etc...
Major Change Examples:
- changing sentence structure for better clarity
- changing menu text for consistency
- getting rid of -chan, -san - and -sama everywhere( I replaced sama with some titles, but -chan and -san were just deleted)
- adding translations for random small things that were missed
etc...

2023-12-26 02:03 UTC, lostcause120 commented
textfile with original text along with change below them
[textchanges.txt](https://github.com/DazedMTL/NightmareKnight/files/13767916/textchanges.txt)

2023-12-28 04:43 UTC, dazedanon requested changes
Everything looks good, just have the gitignore include the pictures and I'll merge it.

2023-12-28 04:43 UTC, dazedanon commented on .gitignore
These images need to be left as is.

2023-12-28 04:45 UTC, dazedanon approved these changes
Actually I'll just merge and make the gitignore changes myself.

2023-12-28 04:45 UTC, merged

2023-12-29 01:52 UTC, lostcause120 commented on .gitignore
Ah thanks, wasn't sure which images you referring to and still not familiar with github.